### ISSUE TITLE
memory issue on startup in some browsers

### ISSUE THREAD

**Issue by losso3000** [losso3000/coppenheimer#2]
(Moved from discussions, as project issues were not activated yet, see discussion entry https://github.com/losso3000/coppenheimer/discussions/1 by @mithrendal)

JavaScript error on fresh start, esp. when clicking "Install AROS ROMs", in `memimage_data.data.set(memdump_buffer)`. Confirmed by another independent bug report.

I finally managed to reproduce this issue with Edge under Windows 11 when using a custom system-wide display scale setting of 117 (probably happens with other "odd" values as well). So this seems to be related with DPI/pixel calculations; setting the canvas size to fill the window uses some (hacky) DOM element pixel calculations that might end up in fractional values and break the assumption that MEM_HPIXELS/MEM_VPIXELS are always integer values.

**Comment by losso3000** [comment]
Live on https://coppenheimer.heckmeck.de/ (0.1.0-alpha3) with commit fc70489a52b28549208ce7b943e29005a9a659c3 which fixes this issue for me; needs confirmation

**Comment by mithrendal** [comment]
retested on browsers that were previously exhibiting the problem

* macOS firefox - works fine
* win11 chrome - works fine
* win11 edge - works fine


good job ! 😎

**Comment by losso3000** [comment]
Thanks for the instant QA!

**Comment by losso3000** [comment]
Closing this, then. Yay 🙂
